
================================================================================
FEDERATED LEARNING BENCHMARK - 2025-07-23T07:27:26.296568
Dataset: cifar10
Number of clients: 50
Batch size: 32
Local epochs: 5
Desired accuracy: 0.9000
Maximum rounds: 500
Device in use: GPU
  GPU per client: 1.0
[92mINFO [0m:      Starting Flower ServerApp, config: num_rounds=500, no round_timeout
[92mINFO [0m:      
[92mINFO [0m:      [INIT]
[92mINFO [0m:      Using initial global parameters provided by strategy
[92mINFO [0m:      Starting evaluation of initial global parameters
Round 0 - Server-side evaluation: loss 2.4702, accuracy 0.1014
[92mINFO [0m:      initial parameters (loss, other metrics): 2.4701771926575193, {'accuracy': 0.1014}
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 1]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
[93mWARNING [0m:   No fit_metrics_aggregation_fn provided
Round 1 - Server-side evaluation: loss 2.9026, accuracy 0.1132
[92mINFO [0m:      fit progress: (1, 2.9026276516838196, {'accuracy': 0.1132}, 143.03044403199965)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 2]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[91mERROR [0m:     An exception was raised when processing a message by RayBackend
[91mERROR [0m:     [36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>
[91mERROR [0m:     Traceback (most recent call last):
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 480, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

[91mERROR [0m:     An exception was raised when processing a message by RayBackend
[91mERROR [0m:     [36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>
[91mERROR [0m:     Traceback (most recent call last):
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 480, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20996, ip=10.120.17.181, actor_id=f3de76998d5cd7cc0896475801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa1ec537940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 48 results and 2 failures
Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).
Round 2 - Server-side evaluation: loss 2.9964, accuracy 0.1598
[92mINFO [0m:      fit progress: (2, 2.9964461219958225, {'accuracy': 0.1598}, 303.99981141299986)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 3x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 3x across cluster][0m
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 3]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 27x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 27x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 3 - Server-side evaluation: loss 2.0551, accuracy 0.3540
[92mINFO [0m:      fit progress: (3, 2.0551285012461507, {'accuracy': 0.354}, 522.8427422059999)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 4]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 4 - Server-side evaluation: loss 1.5030, accuracy 0.5385
[92mINFO [0m:      fit progress: (4, 1.5030139678964218, {'accuracy': 0.5385}, 695.8360103099999)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 5]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 5 - Server-side evaluation: loss 1.2320, accuracy 0.6191
[92mINFO [0m:      fit progress: (5, 1.2319514316301376, {'accuracy': 0.6191}, 866.6898575789996)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 6]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 4x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 4x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).
Round 6 - Server-side evaluation: loss 1.1417, accuracy 0.6515
[92mINFO [0m:      fit progress: (6, 1.1417233878240798, {'accuracy': 0.6515}, 1007.5680277320002)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 3x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 3x across cluster][0m
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 7]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 27x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 27x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 7 - Server-side evaluation: loss 1.0254, accuracy 0.6780
[92mINFO [0m:      fit progress: (7, 1.0254057444893896, {'accuracy': 0.678}, 1129.6920165819997)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 8]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 8 - Server-side evaluation: loss 0.9544, accuracy 0.6984
[92mINFO [0m:      fit progress: (8, 0.9544370638105435, {'accuracy': 0.6984}, 1298.999353222)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 9]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 9 - Server-side evaluation: loss 0.9005, accuracy 0.7149
[92mINFO [0m:      fit progress: (9, 0.9005125251631386, {'accuracy': 0.7149}, 1929.640764235)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 10]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 10 - Server-side evaluation: loss 0.8402, accuracy 0.7293
[92mINFO [0m:      fit progress: (10, 0.8401866815151117, {'accuracy': 0.7293}, 2094.5618222219996)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 11]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 7x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 7x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).
Round 11 - Server-side evaluation: loss 0.7900, accuracy 0.7436
[92mINFO [0m:      fit progress: (11, 0.7899549293537109, {'accuracy': 0.7436}, 2189.0112651229997)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 3x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 3x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 12x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 12x across cluster][0m
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 12]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 11x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 11x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 12 - Server-side evaluation: loss 0.7382, accuracy 0.7594
[92mINFO [0m:      fit progress: (12, 0.7382147439276449, {'accuracy': 0.7594}, 2280.149758821)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 13]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 13 - Server-side evaluation: loss 0.6965, accuracy 0.7718
[92mINFO [0m:      fit progress: (13, 0.6965460290733617, {'accuracy': 0.7718}, 2454.479801991)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 14]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 14 - Server-side evaluation: loss 0.6819, accuracy 0.7796
[92mINFO [0m:      fit progress: (14, 0.6819171990259006, {'accuracy': 0.7796}, 2626.3855987459997)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 15]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 15 - Server-side evaluation: loss 0.6386, accuracy 0.7922
[92mINFO [0m:      fit progress: (15, 0.6385936512829016, {'accuracy': 0.7922}, 2798.169604022)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 16]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 16 - Server-side evaluation: loss 0.5961, accuracy 0.8073
[92mINFO [0m:      fit progress: (16, 0.5961036323168026, {'accuracy': 0.8073}, 2967.946754962)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 17]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 17 - Server-side evaluation: loss 0.5767, accuracy 0.8149
[92mINFO [0m:      fit progress: (17, 0.5766585916756822, {'accuracy': 0.8149}, 3140.9583790659995)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 18]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 18 - Server-side evaluation: loss 0.5480, accuracy 0.8248
[92mINFO [0m:      fit progress: (18, 0.5480387088494559, {'accuracy': 0.8248}, 3308.528419162)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 19]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 19 - Server-side evaluation: loss 0.5237, accuracy 0.8328
[92mINFO [0m:      fit progress: (19, 0.5237426309587475, {'accuracy': 0.8328}, 3495.0223806439994)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 20]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 20 - Server-side evaluation: loss 0.5015, accuracy 0.8410
[92mINFO [0m:      fit progress: (20, 0.5015447715791269, {'accuracy': 0.841}, 3661.971188663)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 21]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 21 - Server-side evaluation: loss 0.4779, accuracy 0.8473
[92mINFO [0m:      fit progress: (21, 0.4778989807437784, {'accuracy': 0.8473}, 3880.4871730829996)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 22]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 22 - Server-side evaluation: loss 0.4548, accuracy 0.8551
[92mINFO [0m:      fit progress: (22, 0.4548017849413732, {'accuracy': 0.8551}, 4059.70003057)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 23]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 23 - Server-side evaluation: loss 0.4489, accuracy 0.8582
[92mINFO [0m:      fit progress: (23, 0.4488942128972124, {'accuracy': 0.8582}, 4316.082469068)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 24]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 24 - Server-side evaluation: loss 0.4345, accuracy 0.8637
[92mINFO [0m:      fit progress: (24, 0.4344651740484725, {'accuracy': 0.8637}, 4491.640647778)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 25]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 25 - Server-side evaluation: loss 0.4146, accuracy 0.8705
[92mINFO [0m:      fit progress: (25, 0.41459456362282504, {'accuracy': 0.8705}, 4703.933982971999)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 26]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[91mERROR [0m:     An exception was raised when processing a message by RayBackend
[91mERROR [0m:     [36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>
[91mERROR [0m:     Traceback (most recent call last):
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 480, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=20995, ip=10.120.17.181, actor_id=c4c5a2d058082bfbd7eb33fb01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feb20337940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/uoft-cs/cifar10/paths-info/0b2714987fa478483af9968de7c934580d0bb9a2

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20996)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Using the latest cached version of the dataset since uoft-cs/cifar10 couldn't be found on the Hugging Face Hub[32m [repeated 5x across cluster][0m
[36m(ClientAppActor pid=20995)[0m Found the latest cached dataset configuration 'plain_text' at /home/dd/.cache/huggingface/datasets/uoft-cs___cifar10/plain_text/0.0.0/0b2714987fa478483af9968de7c934580d0bb9a2 (last modified on Wed Jul 23 07:29:48 2025).[32m [repeated 5x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 49 results and 1 failures
Round 26 - Server-side evaluation: loss 0.3875, accuracy 0.8790
[92mINFO [0m:      fit progress: (26, 0.3874919126851681, {'accuracy': 0.879}, 4851.299692144999)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 27]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 27 - Server-side evaluation: loss 0.3814, accuracy 0.8825
[92mINFO [0m:      fit progress: (27, 0.381380099517564, {'accuracy': 0.8825}, 5023.3560536429995)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 28]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 28 - Server-side evaluation: loss 0.3687, accuracy 0.8867
[92mINFO [0m:      fit progress: (28, 0.3687216986339694, {'accuracy': 0.8867}, 5558.646671652999)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 29]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 29 - Server-side evaluation: loss 0.3628, accuracy 0.8878
[92mINFO [0m:      fit progress: (29, 0.362849514764814, {'accuracy': 0.8878}, 5719.489333725)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 30]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 30 - Server-side evaluation: loss 0.3370, accuracy 0.8990
[92mINFO [0m:      fit progress: (30, 0.3370265972714264, {'accuracy': 0.899}, 5884.141262751)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 31]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 31 - Server-side evaluation: loss 0.3414, accuracy 0.8965
[92mINFO [0m:      fit progress: (31, 0.34142141808836035, {'accuracy': 0.8965}, 6062.4409398259995)
[92mINFO [0m:      configure_evaluate: strategy sampled 25 clients (out of 50)
[92mINFO [0m:      aggregate_evaluate: received 25 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 32]
[92mINFO [0m:      configure_fit: strategy sampled 50 clients (out of 50)
[92mINFO [0m:      aggregate_fit: received 50 results and 0 failures
Round 32 - Server-side evaluation: loss 0.3175, accuracy 0.9079

================================================================================
🎉 RESULT: Desired accuracy 0.9000 reached in 32 rounds!
DATASET: cifar10, CLIENTS: 50, LOCAL_EPOCHS: 5
Time elapsed: 1:43:52.913265
================================================================================

Combined accuracy plot saved to plots/cifar10_50clients_accuracy_plots.png

--- COMPLETE ---
SUCCESS condition met. Terminating simulation for cifar10 with 50 clients.
